version: '3'

services:
  frontend:
    image: undefined01/njupshwfrontend:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    depends_on:
      - backend

  backend:
    image: undefined01/njupshwserver:main
    volumes:
      - ./data:/app/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=PathPrefix(`/api`) || PathPrefix(`/swagger`)"
      - "traefik.http.services.backend.loadbalancer.server.port=80"

  reverse-proxy:
    image: traefik:v2.10
    command:
      - "--log.level=INFO"
      - "--api.insecure=true"
      - "--api.dashboard=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "8429:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
