name: Build and Deploy to Kubernetes
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

defaults:
  run:
    shell: bash

env:
  deploy_environment: >
    {
      "refs/heads/main": "prod",
      "refs/heads/develop": "dev"
    }

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.info.outputs.tag }}
      revision: ${{ steps.info.outputs.revision }}
      reponame: ${{ steps.info.outputs.reponame }}
      reponame_lowercase: ${{ steps.info.outputs.reponame_lowercase }}
      deploy_environment: ${{ steps.info.outputs.deploy_environment }}
    steps:
      - uses: actions/checkout@v3

      - name: Extract commit info
        id: info
        run: |
          tag="$(git describe --tags 2>/dev/null)" || true
          date="$(git log -1 --pretty='format:%cd' --date=short 2>/dev/null)"
          hash="$(git log -1 --pretty='format:%h' 2>/dev/null)"
          test "$tag" && revision="$tag-$hash" || revision="$date-$hash"
          echo "tag=$tag"
          echo "revision=$revision"
          echo "deploy_environment=$(echo '${{ env.deploy_environment }}' | jq -r '."${{ github.ref }}"')"
          echo "tag=$tag" >> "$GITHUB_OUTPUT"
          echo "revision=$revision" >> "$GITHUB_OUTPUT"
          echo "deploy_environment=$(echo '${{ env.deploy_environment }}' | jq -r '."${{ github.ref }}"')" >> "$GITHUB_OUTPUT"
          test "$reponame" || reponame="${GITHUB_REPOSITORY##*/}"
          test "$reponame_lowercase" || reponame_lowercase="${reponame,,}"
          echo "reponame=$reponame"
          echo "reponame_lowercase=$reponame_lowercase"
          echo "reponame=$reponame" >> "$GITHUB_OUTPUT"
          echo "reponame_lowercase=$reponame_lowercase" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        if: ${{ secrets.DOCKER_HUB_USERNAME != '' && secrets.DOCKER_HUB_ACCESS_TOKEN != '' }}
        with:
          username: '${{ secrets.DOCKER_HUB_USERNAME }}'
          password: '${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}'

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./deployment/Dockerfile
          build-args: REVISION=${{ steps.info.outputs.revision }}
          push: ${{ github.event_name != 'pull_request' && secrets.DOCKER_HUB_USERNAME != '' && secrets.DOCKER_HUB_ACCESS_TOKEN != '' }}
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.info.outputs.reponame_lowercase }}:${{ github.ref_name }}
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.info.outputs.reponame_lowercase }}:${{ steps.info.outputs.revision }}

      - name: Extract build results
        run: |
          container_id=$(docker create "${{ secrets.DOCKER_HUB_USERNAME }}/${{ steps.info.outputs.reponame_lowercase }}:${{ steps.info.outputs.revision }}")
          docker cp "$container_id:/app" "./app"
          docker cp "$container_id:/app/swagger.json" "swagger.json"
          docker rm "$container_id"
          zip -r app.zip app

      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: app.zip

      - uses: actions/upload-artifact@v3
        with:
          name: swagger
          path: swagger.json

  deploy:
    needs: build
    if: ${{ needs.build.outputs.deploy_environment != 'null' }}
    runs-on: ubuntu-latest
    environment: ${{ needs.build.outputs.deploy_environment }}
    steps:
      - uses: actions/checkout@v3

      - uses: azure/setup-kubectl@v3
      - uses: azure/k8s-set-context@v3
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Deploy to Kubernetes
        uses: Azure/k8s-deploy@v4
        with:
          namespace: ${{ secrets.KUBE_NAMESPACE }}
          manifests: |
            deployment/deployment.yml
            deployment/service.yml
          images:
            ${{ secrets.DOCKER_HUB_USERNAME }}/${{ needs.build.outputs.reponame_lowercase }}:${{ needs.build.outputs.revision }}
  
  swagger-codegen:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: swagger

      - name: Generate typescript client
        run: |
          test "${{ needs.build.outputs.tag }}" && revision="${{ needs.build.outputs.tag }}" && revision="${revision#v}" || revision="${{ needs.build.outputs.revision }}"

          docker run --rm -v ${PWD}:/app openapitools/openapi-generator-cli generate \
            -i /app/swagger.json \
            -g typescript-fetch \
            -o /app/nju-ps-hw-api \
            --additional-properties=npmName="nju-ps-hw-api",npmVersion="$revision",supportsES6="true",useSingleRequestParameter="false"

          zip -r ts-client.zip nju-ps-hw-api

      - uses: actions/upload-artifact@v3
        with:
          name: ts-client
          path: ts-client.zip

      - name: Generate csharp client
        run: |
          test "${{ needs.build.outputs.tag }}" && revision="${{ needs.build.outputs.tag }}" && revision="${revision#v}" || revision="${{ needs.build.outputs.revision }}"

          docker run --rm -v ${PWD}:/app openapitools/openapi-generator-cli generate \
            -i /app/swagger.json \
            -g csharp \
            -o /app/Api \
            --additional-properties=packageName="NjuCsCmsHelper.Server.Api",packageVersion="$revision",targetFramework="net7.0",library="httpclient",netCoreProjectFile="true",nullableReferenceTypes="true"

          zip -r cs-client.zip Api

      - uses: actions/upload-artifact@v3
        with:
          name: cs-client
          path: cs-client.zip
  
  publish-codegen:
    runs-on: ubuntu-latest
    needs: swagger-codegen
    if: needs.build.outputs.tag != ''
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app
      - uses: actions/download-artifact@v3
        with:
          name: swagger
      - uses: actions/download-artifact@v3
        with:
          name: ts-client
      - uses: actions/download-artifact@v3
        with:
          name: cs-client

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*"
          token: ${{ secrets.GITHUB_TOKEN }}
