name: Build
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:
    branches:
      - "**"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.info.outputs.tag }}
      revision: ${{ steps.info.outputs.revision }}
      reponame: ${{ steps.info.outputs.reponame }}
      reponame_lowercase: ${{ steps.info.outputs.reponame_lowercase }}
    steps:
      - uses: actions/checkout@v3

      - name: Extract commit info
        id: info
        run: |
          tag="$(git describe --tags 2>/dev/null)" || true
          date="$(git log -1 --pretty='format:%cd' --date=short 2>/dev/null)"
          hash="$(git log -1 --pretty='format:%h' 2>/dev/null)"
          test "$tag" && revision="$tag-$hash" || revision="$date-$hash"
          echo "::set-output name=tag::$tag"
          echo "::set-output name=revision::$revision"
          test "$reponame" || reponame="${GITHUB_REPOSITORY##*/}"
          test "$reponame_lowercase" || reponame_lowercase="${reponame,,}"
          echo "::set-output name=reponame::$reponame"
          echo "::set-output name=reponame_lowercase::$reponame_lowercase"

      - name: Build docker image
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./deployment/Dockerfile
          build-args: REVISION=${{ steps.info.outputs.revision }}
          tags: |
            ${{ steps.info.outputs.reponame_lowercase }}:${{ steps.info.outputs.revision }}

      - name: Extract build results
        run: |
          container_id=$(docker create "${{ steps.info.outputs.reponame_lowercase }}:${{ steps.info.outputs.revision }}")
          docker cp "$container_id:/app" "./app"
          docker cp "$container_id:/app/swagger.json" "swagger.json"
          docker rm "$container_id"
          zip -r app.zip app

      - uses: actions/upload-artifact@v3
        with:
          name: app
          path: app.zip

      - uses: actions/upload-artifact@v3
        with:
          name: swagger
          path: swagger.json
  
  swagger-codegen:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: swagger

      - name: Generate typescript client
        run: |
          test "${{ needs.build.outputs.tag }}" && revision="${{ needs.build.outputs.tag }}" && revision="${revision#v}" || revision="${{ needs.build.outputs.revision }}"

          docker run --rm -v ${PWD}:/app openapitools/openapi-generator-cli generate \
            -i /app/swagger.json \
            -g typescript-fetch \
            -o /app/nju-ps-hw-api \
            --additional-properties=npmName="nju-ps-hw-api",npmVersion="$revision",supportsES6="true",useSingleRequestParameter="false"

          zip -r ts-client.zip nju-ps-hw-api

      - uses: actions/upload-artifact@v3
        with:
          name: ts-client
          path: ts-client.zip

      - name: Generate csharp client
        run: |
          test "${{ needs.build.outputs.tag }}" && revision="${{ needs.build.outputs.tag }}" && revision="${revision#v}" || revision="${{ needs.build.outputs.revision }}"

          docker run --rm -v ${PWD}:/app openapitools/openapi-generator-cli generate \
            -i /app/swagger.json \
            -g csharp-netcore \
            -o /app/Api \
            --additional-properties=packageName="NjuCsCmsHelper.Server.Api",packageVersion="$revision",targetFramework="net6.0",library="httpclient",netCoreProjectFile="true",nullableReferenceTypes="true"

          zip -r cs-client.zip Api

      - uses: actions/upload-artifact@v3
        with:
          name: cs-client
          path: cs-client.zip
  
  publish:
    runs-on: ubuntu-latest
    needs: swagger-codegen
    if: needs.build.outputs.tag != ''
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: app
      - uses: actions/download-artifact@v3
        with:
          name: swagger
      - uses: actions/download-artifact@v3
        with:
          name: ts-client
      - uses: actions/download-artifact@v3
        with:
          name: cs-client

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "*"
          token: ${{ secrets.GITHUB_TOKEN }}
